server:
  port: 8097

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

